### PR TITLE
add shadowDom support

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by reppners** [comment]
Thanks for bringing this up and providing your code and experience with shadow DOM back to the community!

Seems not much of a risk factor to get this into the next version (I'm thinking the next version should bump the major just to be safe and not break anyone). 

If you are able to add a custom element to the demo that would be awesome. As simple as it can get, maybe adding just one item at the top list of items in the demo is sufficient to give me a sample for testing/playing.

**Comment by jogibear9988** [comment]
I tried to work on a demo, but your demo project does not work on my system.
I did "npm run start" and got this errors:

image

**Comment by reppners** [comment]
Can you rebase on latest master and perform a fresh npm install? I've updated all the devDependencies to latest versions and I'm seeing no issues with latest Chrome.

**Comment by jogibear9988** [comment]
@reppners 
if now added a web component to the sample.
You needed an additional fix, so the pointer-events in all elements of the shadow dom are disabled.
This was not needed in my case, cause I don't use the "copied element" during drag, and also it is not below mouse cursor

**Comment by jogibear9988** [comment]
@reppners 
any news?

**Comment by danziv** [comment]
@reppners can this be merged?

**Pull request merged**
